apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-core
  labels:
    app: chatbot-core
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot-core
  template:
    metadata:
      labels:
        app: chatbot-core
    spec:
      containers:
      - name: chatbot-core
        image: ${DOCKER_REGISTRY}/ai-customer-support/chatbot-core:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: ai-support-config
              key: redis-url
        - name: VECTOR_DB_URL
          value: "http://memory-engine:3001"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ai-support-secrets
              key: openai-api-key
        - name: LOG_LEVEL
          value: "info"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-core
spec:
  selector:
    app: chatbot-core
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
